### ISSUE TITLE
Creating database Schema

### ISSUE THREAD

**Issue by georgiosbirmpakos** [GeorgeBirb/ticketProject#1]
Creating database Schema

**Comment by GeorgeBirb** [comment]
Database Successfully created
[ticket_booking.zip](https://github.com/GeorgeBirb/ticketProject/files/10279891/ticket_booking.zip)
![TICKET_BOOKING](https://user-images.githubusercontent.com/53330328/208967281-e482f1d1-796b-4a8c-9d2a-ee60d5d6a1e0.JPG)
